export enum DEPTH {
    BACKGROUND_LOWEST = 1,
    BACKGROUND_LOW = 2,
    BACKGROUND_MEDIUM = 3,
    BACKGROUND_HIGH = 4,
    BACKGROUND_HIGHEST = 5,
    OBJECT_LOWEST = 6,
    OBJECT_LOW = 7,
    OBJECT_MEDIUM = 8,
    OBJECT_HIGH = 9,
    OBJECT_HIGHEST = 10,
}
